# Configura��es do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bookanga_db
spring.datasource.username=bookanga
spring.datasource.password=bookanga123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��es do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Desabilita data.sql antigo
spring.sql.init.mode=never

# log
#logging.level.com.products.controller=DEBUG
#logging.level.org.springframework=DEBUG

# validation
spring.mvc.throw-exception-if-no-handler-found=true
